"""Assemble the final engagement report markdown (Phase 6, spec §6.7 step 4).

The Report Agent (``autored.agents.report``) calls this helper after the
four report sub-agents (ExecSummaryWriter, TechReportWriter, MITREMapper,
LessonExtractor) have produced their sections. The output is the full
``engagements/<id>/report.md`` document — the deliverable of record; PDF
is rendered afterwards (graceful degradation when WeasyPrint is missing).

Layout (top → bottom):

1. ``# AutoRed Engagement Report`` title
2. Engagement metadata table (id, target, operator, started, duration,
   parent engagement)
3. ``---`` separator
4. Executive summary markdown (LLM-written, template fallback)
5. ``---`` separator
6. Technical report markdown (LLM narrative + deterministic tables)
7. MITRE ATT&CK matrix table (or empty placeholder when no mappings)
8. Footer with the generated-at timestamp

The assembler is a pure function — no I/O, no LLM, no config — so unit
tests can drive it without any mocks (``tests/unit/reporting/test_markdown_report.py``).
"""
from __future__ import annotations

from datetime import datetime


def assemble_markdown_report(
    state,
    exec_markdown: str,
    tech_markdown: str,
    mitre_mappings: list,
) -> str:
    """Combine the sub-agent outputs into the final report document.

    Layout: title + engagement metadata → executive summary → technical
    report (narrative + deterministic sections) → MITRE ATT&CK matrix →
    generated footer.
    """
    duration_min = max(
        0.0, (datetime.utcnow() - state.started_at).total_seconds() / 60,
    )
    header = [
        "# AutoRed Engagement Report",
        "",
        "| Field | Value |",
        "|---|---|",
        f"| Engagement | {state.engagement_id} |",
        f"| Target | {', '.join(state.target_scope)} |",
        f"| Operator | {state.operator} |",
        f"| Started | {state.started_at.isoformat()} |",
        f"| Duration | {duration_min:.0f} minutes |",
        f"| Parent engagement | {state.parent_engagement_id or '—'} |",
        "",
        "---",
        "",
    ]

    if mitre_mappings:
        matrix = [
            "## MITRE ATT&CK Matrix",
            "",
            "| Technique ID | Name | Tactic | Source | Detail |",
            "|---|---|---|---|---|",
        ]
        for m in mitre_mappings:
            matrix.append(
                f"| {m.technique_id} | {m.technique_name} | {m.tactic} | "
                f"{m.source} | {m.detail} |"
            )
        matrix.append("")
    else:
        matrix = [
            "## MITRE ATT&CK Matrix", "",
            "_No ATT&CK-mapped activity recorded._", "",
        ]

    footer = [
        "---",
        "",
        f"*Generated by AutoRed at {datetime.utcnow().isoformat()}*",
        "",
    ]

    return "\n".join(
        header
        + [exec_markdown, "", "---", "", tech_markdown, ""]
        + matrix
        + footer
    )
